import Navigation from "@/components/Navigation";
import "./globals.css";

import { Inter } from "next/font/google";
import QueryProvider from "@/components/QueryProvider";
import RecommendationProvider from "@/providers/RecommendationProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <RecommendationProvider>
            <Navigation />
            {children}
          </RecommendationProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
